// Editorial sections are maintained separately from the page layout. No legal
// outcome, office location or case history is inferred from a template.
export const sharedSections = {
  assessment: ['A careful first assessment', 'A useful first meeting starts with a chronology: what happened, when it happened, who was involved and what outcome the client actually needs. A lawyer should read the important papers before suggesting a notice, application, agreement or court case. Dates, signed documents, payment records and earlier orders can change the available options. Clients should distinguish facts they know personally from what someone else told them. That distinction helps identify missing proof. Advice can then address the applicable forum, the documents still needed and the practical consequences of each option. A short conversation without the papers may identify urgent steps, but it cannot replace a proper review.'],
  documents: ['Organising the documents', 'Keep originals secure and provide legible copies for the first review. Arrange papers by date and include the complete agreement or order, rather than isolated screenshots of a favourable paragraph. Messages should show dates, senders and enough context to understand the exchange. Where money is involved, bank entries, receipts and tax records may need reconciliation. Where identity or family status matters, obtain the relevant official records. A lawyer can identify gaps and advise how to obtain copies from the correct issuing authority. Do not alter a document, annotate the only original or assume that a social media image will be accepted as a certified record.'],
  objectives: ['Defining the desired outcome', 'A client may want an injunction, a negotiated settlement, a corrected record, payment, lawful possession or a workable parenting arrangement. These are different objectives and may require different legal steps. List the outcome you need now and what would be acceptable if the ideal result cannot be achieved. Discuss the likely time, cost and practical effect before choosing a route. Some disputes involve several separate remedies, each with its own requirements. A lawyer should explain which request can be made in the chosen forum and which issue needs a separate proceeding. This prevents a broad but ineffective claim from obscuring the relief that matters.'],
  jurisdiction: ['Choosing the appropriate forum', 'The place where a party lives, where events occurred, where property is situated and the kind of relief requested may affect which authority or court should receive a matter. An incorrect forum can delay an otherwise sound case. Some steps also begin before a registrar, government office or regulator rather than a court. Ask counsel to identify the forum and the basis for choosing it, especially when the parties are in different cities or countries. Location alone does not resolve every jurisdiction question. The governing law, applicable procedure and documents should be checked together before filing or promising a particular timeline.'],
  communication: ['Keeping instructions clear', 'Agree who will be the main contact, which number or email will be used and how urgent developments will be reported. Send new notices and hearing dates promptly, even if they seem routine. Keep advice, fee discussions and instructions in a retrievable form. If several relatives or company officers are involved, decide who is authorised to instruct counsel and sign documents. Unclear instructions can produce inconsistent positions or missed deadlines. A lawyer should explain the next step in plain language and distinguish an expected procedural step from a guaranteed outcome. The client should also disclose unfavourable facts early enough for them to be addressed responsibly.'],
  fees: ['Understanding scope and fees', 'The cost of legal work depends on the documents, forum, urgency and work actually required. Ask for a clear description of what the quoted fee covers, whether court fees or third-party charges are separate, and what would trigger additional work. A consultation, drafting a notice, filing a case and appearing at hearings are distinct tasks. Avoid relying on an online price quoted for a different city or a different set of facts. Written scope helps both sides understand who will gather records, arrange attestations and communicate with public offices. It also makes it easier to compare realistic options before work begins.'],
  timing: ['Timing and urgent protection', 'Legal rights can be affected by delay, but urgency should be based on the actual facts. Preserve the relevant evidence, record dates of service and tell your lawyer about a hearing, threatened disposal of property, arrest concern or imminent transaction. Some remedies may require prompt action or a specific form of application. Others benefit from a considered notice or negotiation first. Do not assume that sending a message automatically pauses a legal deadline. Ask counsel to check limitation, notice requirements and the immediate protective steps available in the particular matter. Procedural timetables vary by forum and case history.'],
  negotiation: ['Negotiation and settlement', 'A negotiated resolution may save time and cost when the other side is willing to engage, but it should be recorded carefully. Define the obligations, dates, method of performance and consequences if an obligation is not met. Consider whether a court order, registration or transfer document is needed to make the agreement effective. Negotiation should not cause important evidence to disappear or a filing deadline to pass. A lawyer can help separate points that can be settled from questions requiring an order or formal record. The aim is a workable and enforceable outcome, not an informal promise that recreates the dispute later.'],
  evidence: ['Evidence and disputed facts', 'A credible case presents a clear account supported by records and witnesses who can speak to the relevant events. It should also address likely objections instead of ignoring them. Save the complete version of electronic conversations and note how a document was obtained. Financial claims should show their calculations and source records. When the other party holds material records, discuss the lawful way to request or produce them. Evidence rules and the weight given to a document differ by proceeding. A lawyer can identify which disputed facts actually matter to the relief sought and avoid spending time on allegations that do not advance the case.'],
  process: ['What happens after instructions', 'After reviewing the papers, counsel may recommend obtaining missing records, sending a formal communication, preparing an application or discussing settlement. If proceedings are needed, the filing is only the beginning: service, responses, interim requests, evidence and hearings may follow. A timetable should be explained as an estimate, not a promise. The client may need to verify a statement, attend a hearing or supply further records. Keep a copy of filed papers and note every next date. An organised file and timely instructions make it easier to respond when the court or opposing party raises a new issue.'],
  review: ['Reviewing the legal position', 'An early assessment may change when new documents, an opposing response or an official record becomes available. Review the objectives at each important stage: is the requested relief still appropriate, what has been proved and what remains uncertain? A lawyer should explain material changes in risk, cost and likely procedure. If an initial approach is not producing progress, the alternatives may include a revised offer, further evidence or a different lawful remedy. This review should be tied to the actual record rather than broad claims about a lawyer’s success rate. No responsible adviser can guarantee how a contested decision will be made.'],
  confidentiality: ['Privacy and sensitive information', 'Many legal enquiries involve family details, financial records, identity documents or allegations about other people. Share them through an appropriate channel and only with people involved in handling the matter. Before forwarding a document, check whether it contains information about children, employees or unrelated third parties. Ask how originals will be returned and who can access a case file. Public pages and online forms should collect only what is needed for initial contact. A first enquiry can describe the issue without publishing a full private history. Detailed papers can be reviewed through an agreed channel once the professional relationship and scope are clear.'],
  cityContact: ['Contacting the correct city team', 'Use the phone number shown for the city relevant to your enquiry and state where the parties, property or proceedings are located. A city contact number helps route the first conversation; it does not establish that every legal step can be completed in that city. If a matter crosses locations, explain both the client’s location and the location of the court, authority or property. An initial call can identify which documents to send and whether a consultation should be in person or remote. Avoid assuming that a remote discussion replaces an appearance or original-document requirement imposed by the relevant authority.'],
  compliance: ['Checking current official requirements', 'Forms, portals, fees and administrative practices can change. Before filing, verify the current requirement with the responsible court, registrar, regulator or official portal. A checklist from an earlier matter may be a useful starting point but may omit a new form or a requirement specific to a party’s status. Keep evidence of submission and any acknowledgement or reference number. If an officer asks for an additional document, record the request and seek clarification where it seems inconsistent with the governing rule. Legal advice should distinguish what legislation requires from what an office currently requests in practice.'],
  followup: ['After an order or document is issued', 'Obtaining an order, certificate or agreement may not end the work. Check names, dates, identity numbers, property descriptions and the exact relief recorded. Ask whether certified copies, registration, service on another party or a subsequent application are needed. Keep the original safely and make complete copies for future use. If the document will be presented abroad, requirements for translation, authentication or recognition should be checked with the receiving authority. A lawyer can explain the next practical step, including enforcement when a party does not comply. An accurate final record reduces later disputes over what was actually decided.'],
}

export const sharedOrder = {
  city: ['assessment','documents','jurisdiction','objectives','communication','fees','process'],
  marriage: ['assessment','documents','jurisdiction','compliance','fees','confidentiality','followup'],
  family: ['assessment','documents','evidence','jurisdiction','negotiation','timing','followup'],
  litigation: ['assessment','documents','timing','evidence','jurisdiction','process','review'],
  business: ['assessment','documents','compliance','objectives','fees','communication','review'],
  general: ['assessment','documents','objectives','jurisdiction','fees','process','review'],
}

export const officialReferences = {
  'court-marriage-services-fees-process-in-pakistan': ['Muslim Family Laws Ordinance, 1961', 'https://pakistancode.gov.pk/pdffiles/administratordf5df7bd70945d88e28f6a85c1a9ef6b.pdf'],
  'online-marriage-karachi-islamabad-lahore-pakistan': ['Muslim Family Laws Ordinance, 1961', 'https://pakistancode.gov.pk/pdffiles/administratordf5df7bd70945d88e28f6a85c1a9ef6b.pdf'],
  'child-adoption-lawyers-pakistan': ['Guardians and Wards Act, 1890', 'https://www.pakistancode.gov.pk/english/UY2FqaJw2-apaUY2Fqa-cJc%3D-sg-jjjjjjjjjjjjj-con-909'],
  'explaining-family-law-rule': ['Family Courts Act, 1964', 'https://pakistancode.gov.pk/english/UY2FqaJw1-apaUY2Fqa-apaUY2Npa5lraQ%3D%3D-sg-jjjjjjjjjjjjj'],
  'criminal-law-in-pakistan': ['Code of Criminal Procedure, 1898', 'https://pakistancode.gov.pk/pdffiles/administrator7db1e56f0f1d39a6e67573ec6b0944e2.pdf'],
  'civil-lawyer': ['Specific Relief Act, 1877', 'https://pakistancode.gov.pk/pdffiles/administratorf257754bbb3c6863d879492bc8cd8f6e.pdf'],
  'family-and-corporate-lawyers-in-pakistan': ['SECP company registration guidance', 'https://www.secp.gov.pk/company-formation/registration-of-company/'],
  'income-tax-return-filing-business-owners-pakistan-records-wealth-statements-fbr-risk': ['FBR income tax return guidance', 'https://www.fbr.gov.pk/categ/file-income-tax-return/51147/80860/71160'],
}
