// Existing WordPress URLs are retained verbatim during the Next.js migration.
export const pages = [
  { slug: 'attorneys-with-unmatched-expertise-in-pakistan-laws-our-expert-attorneys-fight-for-your-right', title: 'Attorneys and Legal Services in Pakistan', group: 'General legal services', summary: 'Legal advice and representation for individuals, families and businesses in Pakistan.', topics: ['Choosing counsel for your matter', 'How an initial consultation works', 'Documents and next steps'], phone: '+92 333 1127830' },
  { slug: 'attorneys-legal-advisors-and-advocates-in-karachi-expert-lawyers-and-consultants-ready-to-assist-you', title: 'Attorneys and Legal Advisors in Karachi', group: 'City services', summary: 'Speak with our Karachi team about family, property, corporate, tax and civil matters.', topics: ['Legal matters we handle in Karachi', 'Preparing for a consultation', 'Karachi office and contact'], phone: '+92 333 1127830' },
  { slug: 'attorneys-and-lawyers-in-islamabad-experienced-legal-consultants-and-advocates-of-qanoon-group-at-your-service', title: 'Attorneys and Lawyers in Islamabad', group: 'City services', summary: 'Practical legal assistance for individuals and businesses in Islamabad.', topics: ['Family and civil matters', 'Business and tax advice', 'Arrange an Islamabad consultation'], phone: '+92 333 1127836' },
  { slug: 'expert-attorneys-and-lawyers-in-rawalpindi-premier-legal-consultants-and-advisors-of-qanoon-group', title: 'Attorneys and Lawyers in Rawalpindi', group: 'City services', summary: 'Legal advice and representation for clients in Rawalpindi and surrounding areas.', topics: ['Selecting the relevant lawyer', 'Documents to bring', 'Contact the Rawalpindi team'], phone: '+92 333 1127831' },
  { slug: 'comprehensive-legal-services-in-punjab-meet-our-team-of-attorneys-advocates-and-legal-consultants-in-lahore', title: 'Attorneys and Legal Services in Lahore', group: 'City services', summary: 'Discuss family, property, business or civil legal matters with the Lahore team.', topics: ['Legal services in Lahore', 'Understanding your options', 'Arrange a Lahore consultation'], phone: '+92 333 1127835' },
  { slug: 'court-marriage-services-fees-process-in-pakistan', title: 'Court Marriage Services in Pakistan', group: 'Marriage and family', summary: 'Learn about eligibility, documents, the Nikah process and registration before arranging a consultation.', topics: ['Eligibility and free consent', 'Identity and marital status documents', 'Nikah, registration and certificate', 'Fees and timing depend on the case'], phone: '+92 333 1127830' },
  { slug: 'online-marriage-karachi-islamabad-lahore-pakistan', title: 'Online Nikah and Marriage Assistance in Pakistan', group: 'Marriage and family', summary: 'Discuss an online Nikah, identity checks, witnesses and documentation with a lawyer before making arrangements.', topics: ['Assessing the parties and jurisdiction', 'Identity, consent and witnesses', 'Registration and use of documents abroad'], phone: '+92 333 1127830' },
  { slug: 'child-adoption-lawyers-pakistan', title: 'Child Adoption and Guardianship Lawyers in Pakistan', group: 'Marriage and family', summary: 'Understand the difference between guardianship arrangements and adoption terminology in Pakistan.', topics: ['Guardianship and the child’s welfare', 'Court process and supporting documents', 'Overseas use of guardianship orders'], phone: '+92 333 1127830' },
  { slug: 'explaining-family-law-rule', title: 'Family Law in Pakistan', group: 'Marriage and family', summary: 'An overview of legal help with marriage, divorce, maintenance, custody and related family disputes.', topics: ['Marriage and divorce matters', 'Child custody and maintenance', 'Preparing records for family proceedings'], phone: '+92 333 1127830' },
  { slug: 'criminal-law-in-pakistan', title: 'Criminal Law in Pakistan', group: 'Disputes and litigation', summary: 'Learn how to seek advice about allegations, investigation, bail and criminal court proceedings.', topics: ['Early advice after an allegation', 'Investigation and bail', 'Court representation and case records'], phone: '+92 333 1127830' },
  { slug: 'civil-lawyer', title: 'Civil Lawyers in Pakistan', group: 'Disputes and litigation', summary: 'Legal assistance for contract, property and other civil disputes.', topics: ['Assessing the claim and documents', 'Notices and settlement options', 'Civil court proceedings'], phone: '+92 333 1127830' },
  { slug: 'family-and-corporate-lawyers-in-pakistan', title: 'Family and Corporate Lawyers in Pakistan', group: 'Business and tax', summary: 'Find legal support for family matters and business obligations through a suitable specialist.', topics: ['Family law consultations', 'Corporate compliance and contracts', 'Choosing a lawyer for each issue'], phone: '+92 333 1127830' },
]

export const blogPosts = [
  { slug: 'income-tax-return-filing-business-owners-pakistan-records-wealth-statements-fbr-risk', title: 'Income Tax Return Filing for Business Owners in Pakistan', summary: 'Records, wealth statements and FBR risk for business owners.', date: '2026-08-31' },
]

export const specialPages = [
  { slug: 'about-us', title: 'About Attorneys of Pakistan', group: 'Company', summary: 'Learn about our approach to legal work and how to arrange a consultation.', topics: ['Our approach', 'Working with a lawyer', 'Where to reach us'] },
  { slug: 'contact-us', title: 'Contact Attorneys of Pakistan', group: 'Company', summary: 'Contact the relevant city team for a consultation about your matter.', topics: ['Karachi office', 'City contact numbers', 'What to include in your enquiry'] },
  { slug: 'comprehensive-privacy-policy-for-attorneys-com-pk', title: 'Privacy Policy', group: 'Company', summary: 'Information about privacy enquiries. Detailed processing terms require review before publication.', topics: ['Contact about privacy', 'Information supplied in enquiries'] },
]

export const allPages = [...pages, ...specialPages]
export const pathFor = slug => `/${slug}/`
